sudo: required

services:
  - postgresql
  
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-server-dev-all
    - postgresql-common
    
env:
  global:
  - PGPORT=5433
  
script:
 - sudo make install
