sudo: required

services:
  - postgresql
  
addons:
  postgresql: "10"
  
before_script:
  - sudo apt-get install postgresql-server-dev-all
  - sudo apt-get install postgresql-common
  
script:
 - sudo make DESTDIR="./" install
