sudo: required

services:
  - postgresql
    
env:
  global:
  - PGPORT=5433

before_script:
  - sudo apt-get install postgresql-server-dev-all
  - sudo apt-get install postgresql-common
  - sudo systemctl restart postgresql.service
  - sudo /etc/init.d/postgresql restart
  
script:
 - sudo make install
