sudo: required

services:
  - postgresql
  
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    
env:
  global:
  - PGPORT=5433

before_script:
  - sudo apt-get install postgresql-server-dev-all
  - sudo apt-get install postgresql-common
  - sudo systemctl restart postgresql.service
  
script:
 - sudo make install
